vm_name             = "fedora-iot"
version_description = "Fedora IoT\n\nhttps://iot.fedoraproject.org/\n\nPacker config: https://github.com/fkrull/atomic-workstation"

os_version = "38.20230419.2"
iso_checksum = "sha256:6f22609cb540e684f0758ad334b1f4e3b31bae54e21a2d2b8d4fc08b35f99c36"
iso_url = "https://dl.fedoraproject.org/pub/alt/iot/38/IoT/x86_64/iso/Fedora-IoT-ostree-x86_64-38-20230419.2.iso"

kickstart                = "ks-fedora-iot.cfg"
ostree_remote            = "https://ostree.fedoraproject.org/iot"
ostree_remote_name       = "fedora-iot"
ostree_remote_contenturl = "mirrorlist=https://ostree.fedoraproject.org/iot/mirrorlist"
ostree_gpg_key           = "/etc/pki/rpm-gpg/"
crypto_policy            = "DEFAULT:SHA1"
vagrantfile_template     = "tpl/vagrantfile.iot.tpl"
install_guest_additions  = "true"
iso_bootloader           = "grub2"
virtualbox_firmware      = "efi"
