vm_name = "fedora34-silverblue"
version_description = "Fedora 34 Silverblue\n\nhttps://silverblue.fedoraproject.org/\n\nPacker config: https://github.com/fkrull/atomic-workstation"

os_version = "34.1.2"
iso_checksum = "sha256:b311ea95bc58a1b5126eeea940001a9e2f90031990378b4381a582141176d03e"
iso_url = "https://dl.fedoraproject.org/pub/fedora/linux/releases/34/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-34-1.2.iso"

kickstart = "ks-fedora34-silverblue.cfg"
ostree_remote = "https://ostree.fedoraproject.org"
ostree_remote_name = "fedora"
ostree_remote_contenturl = "mirrorlist=https://ostree.fedoraproject.org/mirrorlist"
ostree_gpg_key = "/etc/pki/rpm-gpg/"
crypto_policy = "DEFAULT:SHA1"
vagrantfile_template = "tpl/vagrantfile.silverblue.f33.tpl"
systemd_target = "graphical.target"
