vm_name             = "fedora-iot"
version_description = "Fedora IoT\n\nhttps://iot.fedoraproject.org/\n\nPacker config: https://github.com/fkrull/atomic-workstation"

os_version = "37.20221118.0"
iso_checksum = "sha256:5556d8c3bc725ef301c18dae7e1ba43e44c51ea7381506dc463bca71251bbc78"
iso_url = "https://dl.fedoraproject.org/pub/alt/iot/37/IoT/x86_64/iso/Fedora-IoT-ostree-x86_64-37-20221118.0.iso"

kickstart                = "ks-fedora-iot.cfg"
ostree_remote            = "https://ostree.fedoraproject.org/iot"
ostree_remote_name       = "fedora-iot"
ostree_remote_contenturl = "mirrorlist=https://ostree.fedoraproject.org/iot/mirrorlist"
ostree_gpg_key           = "/etc/pki/rpm-gpg/"
crypto_policy            = "DEFAULT:SHA1"
vagrantfile_template     = "tpl/vagrantfile.iot.tpl"
install_guest_additions  = "true"
iso_bootloader           = "grub2"
virtualbox_firmware      = "efi"
